--- 
cache: 
  directories: 
    - $HOME/.m2
    - $HOME/.sonar
jdk: oraclejdk8
language: java
script: "mvn clean install sonar:sonar -Dsonar.projectKey=aroundthecode_pathfinder -Dsonar.organization=aroundthecode-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN"
