cache:
  directories:
  - $HOME/.m2  
jdk: oraclejdk8
language: java
before_deploy:
  - "cp pathfinder-server/target/pathfinder.war webapps/ROOT.war"
deploy:
  provider: openshift
  user: openshift01@aroundthecode.org
  password:
    secure: Pd7No1e+xfJ+Z1QG53KASdNnJ6xaVBqZJrkneNr9WHVtipIRribHdnAectdv/IKbaFqGrRy8gXBsWt6dDFuSwREOzqvFwqkkpRVVNZc0KsehpQUz9WtMyejns7l3FiPfpazhCWwE1NSPQdajkRWvkhs4P7lv+5nHGHAC4A1VNboZ4DJnrhAmMOOpQ8AgAQzay9zjCK0Zgdnjd7J5GBLdeyrqe+kbuXpT8s3mkYJZqSlznU/az191i3O/ZTL0G+UybwGR9a9ymbynOi/lyXvpU1YEK2xm5KehSHuJ55i2NZ5Jx2ChcjBOXFif2jHN6Mie/87oL276r4pAodkt88se1ZBVsMbb/tCJa4+5k/Fokq7gpXdhl38Wwd/Nj3Fg0Q2fzedubIz6IvxSAbtyAfkXNzlcGv8Cjcr2O0q+Mw8lmdD8mr6SQq2pO/qbixgEt7canHztNG3scLR1QYZ3l25NbuGZtrNfninI9nBy7UHUtBW+4v8MSWVbl9IwtK8cEzLJxDD0Z42YyvS6xZn3PTpGOXihr//dBQJsi36KpORaUv5JdMtike2iIUmWHSt2507NaQlSv8JI5/k5OB9Rr7X4psJIkfqwwaiX/w/cBTA3vWhZQV/ns+d5VejOqqF6PH4vt4fzsFHzJ32gdpG5g1r+U60jJXsSCh5PRfscOHNS20g=
  app: pathfinder
  domain: aroundthecode1
  on:
    repo: aroundthecode/pathfinder
    branch: openshift
  skip_cleanup: true
